### ISSUE TITLE
Use dependencies in vendor/ instead of downloading them

### ISSUE THREAD

**Issue by amuttsch** [golang/mock#296]
I have a Go project that uses modules and stores its dependencies in the `vendor/` folder. In our CI pipeline, we install `gomock` and run it via `//go:generate mockgen -source ./foo/service.go -destination gen/foo/mocks.go -package foo`. 

gomock then tries to download all dependencies from its source repositories instead of using the vendor folder. This is problematic for us as we have some dependencies in a private repo that uses self signed certificates. Thats why we want to use the `vendor/` folder.

We execute `go generate -mod vendor` to trigger the generation, we tried prefixing it with `GOFLAGS=-mod=vendor` and using `-build_flags "-mod vendor" `, but gomock always downloads all dependencies.

How can we tell gomock to look for dependencies in the `vendor` folder first before downloading them? Thanks!

**Comment by soniah** [comment]
The standard suggestion is to use `retool` however retool isn't module aware 🤣  There's a blog post [retooling retool](https://npf.io/2019/05/retooling-retool/) about using `mage` to download build tool dependencies, I'm following up on that.

A possible solution to this issue/bug would to make `mockgen` it's own module, so it could be easily vendored using the go mod mechanisms.

**Comment by Logibox** [comment]
I got this working by putting in my go:generate line `-build_flags=-mod=vendor`, no quotes. Must be something funny going on with how `go generate` escapes quotes maybe?

**Comment by soniah** [comment]
Thanks @Logibox. `gomock` is painful to use with modules, they've been going to fix it for a while, hopefully this is a working temporary fix.

**Comment by nguyenfilip** [comment]
@Logibox I made a small fix to address the -build_flags behavior.

@amuttsch  has the workaround with `-build_flags=-mod=vendor` worked in your case? If yes I will consider to add automatic fallback to run _module download mode_ `vendor` if default download mode fails.

@soniah It would be great if you provided some more details about issues you are running into with `gomock` and modules. I can try to think about how to improve that.

**Comment by codyoss** [comment]
@amuttsch @Logibox @soniah Any updates?

**Comment by soniah** [comment]
Hi @nguyenfilip @codyoss I haven't looked at this for ages, I'll have to think through the issues and implications. @nguyenfilip I can't remember the issues I was having.

I'm sure you've looked the HEAD of master; FYI mocks are now built into the `mocks` folder and the build command is described in the `README`. But this seems is a different issue.

@Logibox made the following comment earlier in the thread:

> I got this working by putting in my go:generate line -build_flags=-mod=vendor, no quotes

What results did you get from this @codyoss ? I feel your pain about self signed certs. Have you tried setting up a go mod proxy using [Athens](https://docs.gomods.io/)?

**Comment by nguyenfilip** [comment]
@codyoss @amuttsch @soniah I think this has been fixed by #390 in mockgen  1.4.1. There was a similar problem described in another bug #347 and the OP in that bug confirmed the issue has been fixed for them. In the discussion of the bug I also provided some sample reproducer that shows correct behavior of mockgen+vendoring with mockgen 1.4.1

**Comment by orian** [comment]
The problem is still there, I'm running mockgen:

`mockgen -source external.go -destination mocks/mock.go -build_flags=-mod=vendor` and it persistently trying to fetch the packages (and fails cause some are private).

**Comment by codyoss** [comment]
@orian What version are you using? `mockgen -version`

**Comment by orian** [comment]
`v1.4.3`

**Comment by codyoss** [comment]
@orian Could you open up a new issue and detail a small example of how to reproduce.

**Comment by thynquest** [comment]
Hello 
Any updates on this issue?
Thank you

**Comment by codyoss** [comment]
@thynquest can you provide a small example showing this not working for you. This is a closed issue, so it is not being actively looked at. The original issue has been fixed. Please open a new issue with details to get better traction.
